title: Inklyn Blog
email: hi@inklyn.com
description: Run your business from the USA, while you live where you’re valued most.

url: "https://blog.inklyn.com"
baseurl: ""

user_x: inklyn
user_github:  inklyn
user_linkedin: inklyn
user_instagram: inklyn

# Build settings
theme: minima

markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:slug'

plugins:
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-sitemap
  - jekyll-titles-from-headings

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.md